### ISSUE TITLE
how to do a pixel gun dump files?

### ISSUE THREAD

**Issue by Miyamura4** [stanuwu/PixelGunCheatInternal#14]
Sup, dear git'hubers. I have a problem with il2cpp dumpers. Can anyone help me with?
![image](https://github.com/stanuwu/PixelGunCheatInternal/assets/166149013/f8207061-ee17-4b8c-ba9c-c64690f549b9)
![image](https://github.com/stanuwu/PixelGunCheatInternal/assets/166149013/8121db96-07ea-4c10-9c8d-1345eb6da105)

**Comment by Mezo-hx** [comment]
Simple. The metadata is encrypted.
