### ISSUE TITLE
Bigger menu ?

### ISSUE THREAD

**Issue by Poisonwolf666** [stanuwu/PixelGunCheatInternal#17]
Is it possible to get bigger menu ?,

**Comment by David-M-GitHub** [comment]
you have on right down side you can scale it bigger

**Comment by Poisonwolf666** [comment]
> you have on right down side you can scale it bigger

Yeah thanks inoticed it xD and i have gotten banned sadly,

**Comment by Xash00** [comment]
что ты использовал?за какую функцию забанили?
