### ISSUE TITLE
Game unity crashes after a few minutes

### ISSUE THREAD

**Issue by TXxKo** [stanuwu/PixelGunCheatInternal#43]
loaded injector in lobby, joined a game and a few minutes later i keep crashing with unity.

**Comment by kvux** [comment]
fr

**Comment by xXM4Y021Xx** [comment]
I use "Process Hacker 2" as an injector and no errors occur

**Comment by Fentlover21** [comment]
also crashing while in game, injecting newest version in lobby with ph2 only using esp and aimbot :/

**Comment by SillyBleh** [comment]
provide some information about the crash

**Comment by xXM4Y021Xx** [comment]
> also crashing while in game, injecting newest version in lobby with ph2 only using esp and aimbot :/

Silly question, disable antivirus or Windows Defender before injecting the hack?
