### ISSUE TITLE
no keybinds to open menu

### ISSUE THREAD

**Issue by reallybro133** [stanuwu/PixelGunCheatInternal#52]
i have no clue how to open the menu it's not stated in the readme and the discord link is invalid, please help out a beginner cheater!

**Comment by reallybro133** [comment]
im not sure if i should have but it into the issues or the pull requests 😢

**Comment by NoLifeHackerClanYT** [comment]
> i have no clue how to open the menu it's not stated in the readme and the discord link is invalid, please help out a beginner cheater!

Right-Shift
