### ISSUE TITLE
antivirus doesnt seem to like you

### ISSUE THREAD

**Issue by KoalaBooo** [stanuwu/PixelGunCheatInternal#53]
hey there, seems you have a trojan of some sorts in there, grabbed your old one and it was fine. this one has just been flagged with virus's. can we get some light on that?
![image_2024-05-27_003416346](https://github.com/stanuwu/PixelGunCheatInternal/assets/170914050/c01388ae-90ea-47b6-a560-8269fa18816e)

**Comment by stanuwu** [comment]
changes in code structure can change antivirus flags
