### ISSUE TITLE
[Request] Update weapon and wearable modules to include new IDs

### ISSUE THREAD

**Issue by proudPantry** [stanuwu/PixelGunCheatInternal#55]
hi, the game recently updated and they added a couple armors (steel, gold, diamond etc) and 7 new weapons, can you update the modules to account for the additions?

**Comment by xXM4Y021Xx** [comment]
Can you still use the cheats in that update? (Supposedly they would implement a better anti-cheat system)

**Comment by Zombiekiller4yo** [comment]
> Can you still use the cheats in that update? (Supposedly they would implement a better anti-cheat system)

that's a good question and it doesn't say there's a new anti cheat or show one in game yet

**Comment by stanuwu** [comment]
new ids will not be added but prs are welcome
