### ISSUE TITLE
PixelGunCheat Some of the latest questions be sure to check out

### ISSUE THREAD

**Issue by moroysa** [stanuwu/PixelGunCheatInternal#62]
When injecting into the game hall, all functions fail and crash directly. What is the problem? Is there any abnormality in the program? Please solve it and release the latest patch. I will give you a reward of $100 ，Please, I really need him！

**Comment by mrtophatthe4** [comment]
im pretty sure the offsets arent correct

**Comment by moroysa** [comment]
> 我很确定偏移量不正确

Can we solve the latest offset?

**Comment by stanuwu** [comment]
im pretty sure this should be resolved now, let me know if it still happens

**Comment by mrtophatthe4** [comment]
> im pretty sure this should be resolved now, let me know if it still happens

hey, with sig scanning you can make an auto updating offset feature

**Comment by stanuwu** [comment]
making sigs for il2cpp methods is a bit... special
we are on the 4th version of dumper because they keep patching it so i'd rather not make the way to get offsets public
