### ISSUE TITLE
[Boykisser Central] [ERR] MinHook failed to hook to offset 0x41d5300! (Status: 8) [Boykisser Central] [ERR] MinHook failed to hook to offset 0x11865f0! (Status: 8) [Boykisser Central] [ERR] MinHook failed to hook to offset 0xbb8e00! (Status: 8)

### ISSUE THREAD

**Issue by AgdADGSFGAH** [stanuwu/PixelGunCheatInternal#82]
[Boykisser Central] [ERR] MinHook failed to hook to offset 0x41d5300! (Status: 8)
[Boykisser Central] [ERR] MinHook failed to hook to offset 0x11865f0! (Status: 8)
[Boykisser Central] [ERR] MinHook failed to hook to offset 0xbb8e00! (Status: 8) 
![Uploading image.png…]()

**Comment by galaxykiller758** [comment]
im having the same issues

**Comment by galaxykiller758** [comment]
its pissing me off
