### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by icdmkg2** [stanuwu/PixelGunCheatInternal#83]
im getting this error in the console and if I do anything ingame it just straight up crashes 

`[Boykisser Central] [ERR] MinHook failed to hook to offset 0x41d5300! (Status: 8)
[Boykisser Central] [ERR] MinHook failed to hook to offset 0x11865f0! (Status: 8)
[Boykisser Central] [ERR] MinHook failed to hook to offset 0xbb8e00! (Status: 8)`

**Comment by SebaztianSolace** [comment]
outdated

**Comment by vor1c** [comment]
would jump of a bridge if i was in this situation
